### ISSUE TITLE
 关于：Error: Protocol "https:" not supported. Expected "http:"

### ISSUE THREAD

**Issue by Juliancn** [allanguys/font-spider-plus#1]
关于不支持'https' 的在线地址解析，感觉这是一个大问题。。。。不知道是否能够解决

**Comment by CodeListener** [comment]
![image](https://user-images.githubusercontent.com/26272596/39848526-01cd8876-543a-11e8-9afc-e6ddc9c4a1e5.png)
求问这是什么原因，新手求教

**Comment by gqbre** [comment]
同 @CodeListener  问题，使用 sudo 安装
