### ISSUE TITLE
使用中的问题

### ISSUE THREAD

**Issue by GracefulTing** [allanguys/font-spider-plus#12]
font.css:
@font-face {
  font-family: 'SourceHanSerifCN';
  src: url('SourceHanSerifCN-Bold.ttf');
  font-weight: normal;
  font-style: normal;
}

body{
    font-family: 'SourceHanSerifCN';
}

运行：fsp local index.html如下：
\ 正在优化...not support cmap format:14
√ 没有发现可以优化的自定义字体

重新启动项目发现字体又恢复原来的样式了。

**Comment by allanguys** [comment]
字体文件是ttf格式么？可以把字体文件发上来看下

**Comment by GracefulTing** [comment]
> 字体文件是ttf格式么？可以把字体文件发上来看下

好像发不了ttf文件，不支持这种格式。从网上下载的，是思源宋体SourceHanSerifCN-Regular.ttf

**Comment by mt4c** [comment]
https://github.com/Pal3love/Source-Han-TrueType
这里可以找到
