### ISSUE TITLE
 Unexpected token e in JSON at position 1

### ISSUE THREAD

**Issue by zxhhh11** [allanguys/font-spider-plus#18]
when I run fsp run , the following errors was reported ,

![image](https://user-images.githubusercontent.com/49676144/65296155-2abb3500-db96-11e9-9291-ba6fa6fb352c.png)

and this id my fspconfig.js
![image](https://user-images.githubusercontent.com/49676144/65296362-c3ea4b80-db96-11e9-85f8-1376a290c835.png)
can you help me tell me  how to modify this file  fspconfig.js?

**Comment by allanguys** [comment]
localpath不支持用@哈，用相对路径

**Comment by zhoutengshen** [comment]
这个文件需要严格准守json格式
