### ISSUE TITLE
vue的文件怎么直接使用命令压缩全局的本地文件？

### ISSUE THREAD

**Issue by ZhongHongLi** [allanguys/font-spider-plus#24]
你那个操作本地的那个命令我看了是对应的文件夹不能一下操作吗
![QQ截图20210818101406](https://user-images.githubusercontent.com/28956814/129825712-711f85a3-54d3-4c99-857b-72e0267b9386.png)

**Comment by allanguys** [comment]
压缩本地webFont不支持动态渲染的字体。
没有部署的vue项目，建议本地直接用npm run serve起一个服务，用`压缩URL中的WebFont`配置url压缩
