### ISSUE TITLE
字体文件大小有限制吗

### ISSUE THREAD

**Issue by henudxk** [allanguys/font-spider-plus#5]
10MB以上的字体文件没有压缩
![image](https://user-images.githubusercontent.com/6907217/42868569-3e806bd4-8aa5-11e8-909e-787c7b6f5ec4.png)

**Comment by allanguys** [comment]
可以提供下字体源文件么？

**Comment by henudxk** [comment]
可以






在 2018-07-18 19:10:48，"Allan" <notifications@github.com> 写道：


可以提供下字体源文件么？

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or mute the thread.

从网易163邮箱发来的云附件
PingFangSC-Medium.ttf (10.26M, 2018年8月3日 9:20 到期)
下载
PingFangSC-SemiBold.ttf (10.15M, 2018年8月3日 9:20 到期)
下载

**Comment by allanguys** [comment]
没有收到你的字体，从互联网上找到了PingFangSC-Medium.ttf，用[https://github.com/sindresorhus/file-type](file-type)验证之后其实是otf编码。

**有两个解决方法：**
先把文件命名会otf

- 下载FontCreator转换成ttf格式
- 使用在线转换服务转换成ttf格式  [https://convertio.co/zh/font-converter/](https://convertio.co/zh/font-converter/)

**Comment by henudxk** [comment]
好的，谢谢，我再试试




发自网易邮箱大师
在2018年07月19日 14:35，Allan 写道：

没有收到你的字体，从互联网上找到了PingFangSC-Medium.ttf，用https://github.com/sindresorhus/file-type验证之后其实是otf编码。

有两个解决方法：
先把文件命名会otf

下载FontCreator转换成ttf格式
使用在线转换服务转换成ttf格式 https://convertio.co/zh/font-converter/

**Comment by henudxk** [comment]
确实是字体格式问题
