### ISSUE TITLE
question : 关于支持动态的文本

### ISSUE THREAD

**Issue by PLQin** [allanguys/font-spider-plus#8]
从源代码中并没有发现处理动态文本的相关逻辑 ;

请问作者是如何实现的 ? 

是否有相关详细的api注解

**Comment by YikaJ** [comment]
@PLQin 我看 package.json 里有一个 puppeteer，应该是模拟了一个浏览器环境去渲染页面，并执行 Javascript 逻辑，最后捕获到相应的动态文本。

**Comment by PLQin** [comment]
> @PLQin 我看 package.json 里有一个 puppeteer，应该是模拟了一个浏览器环境去渲染页面，并执行 Javascript 逻辑，最后捕获到相应的动态文本。

所发

**Comment by allanguys** [comment]
是的，使用puppeteer处理的动态文本，但是目前只支持window.load之前的文本数据哈
